// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/data/t2k/phumhh/lbne/srcs/larvalidatereco/larvalidatereco/content/3gev/./LArPIDVarCoreHaloAll.cxx";

#endif
