/********************************************************************
* /data/t2k/phumhh/lbne/srcs/larvalidatereco/larvalidatereco/content/3gev/LArPIDVarCoreHaloAll_cxx_ACLiC_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /data/t2k/phumhh/lbne/srcs/larvalidatereco/larvalidatereco/content/3gev/LArPIDVarCoreHaloAll_cxx_ACLiC_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableLArPIDVarCoreHaloAll_cxx_ACLiC_dict();
extern void G__cpp_setup_inheritanceLArPIDVarCoreHaloAll_cxx_ACLiC_dict();
extern void G__cpp_setup_typetableLArPIDVarCoreHaloAll_cxx_ACLiC_dict();
extern void G__cpp_setup_memvarLArPIDVarCoreHaloAll_cxx_ACLiC_dict();
extern void G__cpp_setup_globalLArPIDVarCoreHaloAll_cxx_ACLiC_dict();
extern void G__cpp_setup_memfuncLArPIDVarCoreHaloAll_cxx_ACLiC_dict();
extern void G__cpp_setup_funcLArPIDVarCoreHaloAll_cxx_ACLiC_dict();
extern void G__set_cpp_environmentLArPIDVarCoreHaloAll_cxx_ACLiC_dict();
}


#include "/tmp/rootcint_VIY3SG.h"
